### ISSUE TITLE
Q: Stable for production?

### ISSUE THREAD

**Issue by LarsKrogJensen** [tools4j/nobark#4]
This really looks like very useful library, but need to ask of production readiness.

Looking for an efficient many-to-many conflating queue

**Comment by LarsKrogJensen** [comment]
AtomicConflationQueue.entryMap is only added to, never removed, potential memory leak unless small set of conflationKey

**Comment by terzerm** [comment]
Hi.  

To your first point yes the library is production ready.  It is used in production in at least 2 financial institutions.  The conflation queues are also used in production.

A many-to-many conflation queue is best achieved with the ManyToManyConcurrentArrayQueue from the agrona library as backing queue.

To your second point you are right --- the conflation queues are designed to work with small repetitive sets of conflation keys, such as currency pair or instrument symbols or IDs.  It works most efficiently with enum keys and with eager map initialisation.

If you have changing keys such as pricing requests or orders then you may want to map your real key to a final set of  conflation keys first.  The conflation keys have to be removed from the backing map from your app when you can guarantee that no entries are in the queue anymore.  This can be achieved by sending a 'terminal' signal through the queue e.g. when the request or order terminates.  When this terminal signal is polled from the queue you know that the key is no longer used and you can remove it from the map.  You will need a thread-safe map for this which is not ideal for performance though.

**Comment by LarsKrogJensen** [comment]
Thanks for respones, and I will explore to suggestion. How do you do with consume polling, there is no blocking poll with timeout ala BlockingQueue, spinwait?

**Comment by terzerm** [comment]
Usually you need no blocking when conflation queues are used.  The consumer consumes as fast as he can and if null is polled it does nothing (or it invokes some idle strategy --- see agrona idle strategies for more information).  For best performance blocking (i.e. locks) and context-switches are always bad.

**Comment by LarsKrogJensen** [comment]
thanks for answers
